### ISSUE TITLE
gravel: feed loopback devices to bootstrap for local node playground?

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#159]
**Is your feature request related to a problem? Please describe.**
Running Aquarium locally without a virtualised environment would require using the host's disks. We should make it easier to test and play around without needing that, nor necessarily needing a VM.

**Describe the solution you'd like**
Loopback devices, file-backed, would be a simple and easy enough approach.

**Additional context**
This may not be feasible. Looking into how cephadm tests bootstrap might be the best path forward here.

**Comment by asettle** [comment]
@l-mb we choose you, Pikachu, to look into this

**Comment by jecluis** [comment]
I don't think this is going to happen any time soon, or at all. Closing until one day we realize we actually need it, or someone volunteers to implement it :)
