### ISSUE TITLE
Support Ubuntu as the host/development environment

### ISSUE THREAD

**Issue by l-mb** [aquarist-labs/aquarium#223]
To improve accessibility of Aquarium, the host and development environment should support other distributions, such as Ubuntu.

Note that this is not a request to migrate the image runtime that we build to something else - just that our documentation and tooling supports building the image on a different environment.

**Comment by ml8mr** [comment]
@AvengerMoJo Is this issue completely addressed by #267 and #272 ?

**Comment by AvengerMoJo** [comment]
@ml8mr yes. The kiwi boxbuild capability allow other distribution using leap or TW in qemu to build the microOS with the same kiwi config. 
One small downside is the boxbuild VM require to download 600MB image. And using qemu to build the image may take a little longer. But the features are completed.
