### ISSUE TITLE
gravel: Can't create CephFS

### ISSUE THREAD

**Issue by Devp00l** [aquarist-labs/aquarium#230]
**Describe the bug**
Can't create CephFS which had worked last Tuesday. Now I get first few tries an error 500 Internal Server Error than a 428 Precondition Required.

Running with "./run_aquarium.sh -d --with-system-deps" I got not more input than without debugging only:
`INFO:     192.168.121.193:34428 - "POST /api/services/create HTTP/1.1" 500 Internal Server Error`
or
`INFO:     192.168.121.193:34780 - "POST /api/services/create HTTP/1.1" 428 Precondition Required`

**To Reproduce**
Have a new cluster and try to create a new CephFS service.

**Expected behavior**
Create a working CephFS service.

**Comment by jecluis** [comment]
428 is not a bug. Just conveying, in this particular case, that the cluster can't meet the requirements for service creation (i.e., too many pgs for the number of osds). The real bug here is detailed in #235
