### ISSUE TITLE
gravel: fix version of containers we consume

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#234]
Right now we are consuming whatever cephadm consumes by default (master, I think). We need to fix a version and stick to it. Otherwise developing against an ever changing orchestrator interface, or whatever, is going to be painful.

A symptom of this has been #230 due to something changing on the Ceph side and biting us.

**Comment by ml8mr** [comment]
After a discussion with a few engineers, let's ignore this for now, but stabilize on an image a couple of weeks before reaching a milestone. We can make a long term decision after Pacific stabilizes.

**Comment by asettle** [comment]
We want to test this on a stable container for milestone 2 - but the demo could be successful without it
