### ISSUE TITLE
doc/from-zero-to-hacking.md: aquarium service isn't running right after bringing new nodes up

### ISSUE THREAD

**Issue by ifed01** [aquarist-labs/aquarium#246]
The "from-zero-to-hacking.md" manual mentions that after new nodes have running aquarium service once they're up for the first time:
"At this point you will have shell access to the node, and it is expected that Aquarium will be running. Accessing http://localhost:1337 (or 1338 depending which node you are trying to access) should be possible, and you should be presented with a nice frontend. If your connection is refused or reset, it might just be that you need to open firewall ports.
"
That's not the case (at least in my env). Manual service start up didn't help too. 
It's running 'sudo /srv/aquarium/run_aquarium.sh" which finally brought the service up. Some additional packages were installed along the path.

**Comment by asettle** [comment]
@l-mb did you experience a similar issue?

**Comment by s0nea** [comment]
I can confirm, same behavior on my environment.

**Comment by s0nea** [comment]
I mean the service is not running at startup. I get the service running by `sudo /srv/aquarium/run_aquarium.sh`.

**Comment by jecluis** [comment]
This might have had something to do with a missing dependency on image build (`python3-websockets`). Can you please retry with the latest `main`?

**Comment by ifed01** [comment]
Even worse these days - I'm unable to start the service, it's always showing:
 aquarium.service - Project Aquarium
     Loaded: loaded (/usr/lib/systemd/system/aquarium.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2021-03-31 14:49:17 UTC; 5min ago
    Process: 2279 ExecStart=/usr/local/bin/uvicorn aquarium:app --host 0.0.0.0 --port 1337 (code=exited, status=1/FAILURE)
   Main PID: 2279 (code=exited, status=1/FAILURE)

Manual run works (more or less) fine though...

**Comment by jecluis** [comment]
can you grab the log that should be in `/tmp/aquarium.log` and paste it somewhere?

**Comment by ifed01** [comment]
when starting the service the log gets nothing... Running the command "/usr/local/bin/uvicorn aquarium:app --host 0.0.0.0 --port 1337" manually returns:
ERROR:    Error loading ASGI app. Could not import module "aquarium".

**Comment by ifed01** [comment]
> This is the weirdest thing. Are the files in `/usr/share/aquarium/`?

Yes, but the look pretty outdated:
vagrant@node01:~> ll /usr/share/aquarium/
total 4
-rw-r--r-- 1 root root 2335 Mar  3 11:48 aquarium.py
drwxr-xr-x 1 root root    8 Mar  3 11:48 glass
drwxr-xr-x 1 root root   64 Mar  3 11:48 gravel

**Comment by ifed01** [comment]
Perhaps I haven't rebuilt the images properly... please hold on

**Comment by ifed01** [comment]
So the issue has been fixed in the latest code. My last issues were caused by improper/incomplete image build.

**Comment by jecluis** [comment]
Thanks for confirming :)
