### ISSUE TITLE
glass: widgets are shrinking and moving on the dashboard on Chrome

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#262]
The widgets 'Capacity' and 'System Information' are shrinking and moving on the dashboard in Chrome. It seems to be related to the donut charts.

![Screenshot_2021-03-08_11-13-43](https://user-images.githubusercontent.com/8761082/110310271-a3b88180-8002-11eb-8817-b5d9be2cee7d.png)

->

![Screenshot_2021-03-08_11-13-14](https://user-images.githubusercontent.com/8761082/110310251-9e5b3700-8002-11eb-8a20-0328cd47a742.png)

**Comment by votdev** [comment]
Can't reproduce this issue with Chrome Version 87.0.4280.88 in [latest](cf862df8545903949e8f1e6384d1f2619fe3929a) `main` branch.

**Comment by s0nea** [comment]
Hmmm... interesting. Happens to me on [latest main](https://github.com/aquarist-labs/aquarium/commit/cf862df8545903949e8f1e6384d1f2619fe3929a) and Chrome `88.0.4324.150`

**Comment by votdev** [comment]
Still not reproducible with 89.0.4389.82 on Ubuntu.

**Comment by asettle** [comment]
Just a side note - the dashboard looks similar to the Ceph dashboard we have (in the sense of the layout, and information presented) :thinking: https://documentation.suse.com/ses/7/single-html/ses-admin/images/dashboard_homepage.png 

It's a lot of information at once. Is the intention to keep it this way, or how we are seeing this design play out?

**Comment by ml8mr** [comment]
> It's a lot of information at once. Is the intention to keep it this way, or how we are seeing this design play out?

IMO, the initial dashboard view should be focused on the overall cluster, so node specific details (e.g. volumes, and system information) aren't necessary.

Is there a mockup showing the final view we are shooting for? (This would be helpful to get feedback on during Hackweek.)

**Comment by s0nea** [comment]
> Still not reproducible with 89.0.4389.82 on Ubuntu.

:smile: it's still happening to me with Chome Version 89.0.4389.82 (Official Build) (64-bit) on openSUSE Leap. Has anyone else tested it (ideally on Leap)?

> It's a lot of information at once. Is the intention to keep it this way, or how we are seeing this design play out?
> Is there a mockup showing the final view we are shooting for? (This would be helpful to get feedback on during Hackweek.)

As far as I know it was the plan to keep these information. @Devp00l please correct me if I'm wrong :wink: If I'm right, I think we should open another issue to clean the dashboard up.

**Comment by votdev** [comment]
> IMO, the initial dashboard view should be focused on the overall cluster, so node specific details (e.g. volumes, and system information) aren't necessary.

PR https://github.com/aquarist-labs/aquarium/pull/298 will fix that by disabling these widgets by default. The user can enable/show them on demand.

**Comment by s0nea** [comment]
I just noticed the issue is gone for me (at least since https://github.com/aquarist-labs/aquarium/commit/6841ce5280d12e0ea2d51d3738effb80c2450e53). Unfortunately I don't know which commit fixed it exactly.
I'm going to close the issue. Feel free to re-open it if you're seeing the behavior again.
