### ISSUE TITLE
glass: Add installer page to join existing cluster

### ISSUE THREAD

**Issue by votdev** [aquarist-labs/aquarium#263]
Add the installer page to join an existing cluster. The page should request the following information from the user: 
- IP/FQDN address of the master node
- Auth token (hex string like xxxx-xxxx-xxxx-xxxx)

After the join progress was successful the installer will redirect to the existing `Deployment` page which shows an overview of the disks are going to be assimilated by the cluster. Additionally services can be created, too.

**Comment by s0nea** [comment]
The page should also show an overview of the disks are going to be assimilated by the cluster.
