### ISSUE TITLE
Live distro for aquarium

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#275]
Someone new to the project might want to test the look and feel, to explore Aquarium a bit, on a real system without having to install Aquarium.

A Live distro would allow us to provide that experience.

**Comment by jecluis** [comment]
@AvengerMoJo do you think this is feasible for milestone 2?

**Comment by AvengerMoJo** [comment]
Just need to make sure someone can help me test the iso. I should able to create the patch today.

**Comment by jecluis** [comment]
I'll be happy to give it a spin once you've got it :)

**Comment by AvengerMoJo** [comment]
https://github.com/AvengerMoJo/aquarium/tree/origin/wip-build-live-iso

Please check this out and build it with `

/bin/bash ./tools/build-image.sh --type live-iso`

**Comment by AvengerMoJo** [comment]
#289 the patch should be working.
