### ISSUE TITLE
gravel: reduce dependency on global instances

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#276]
We have a lot of classes being instantiated at the module level. We might want to consider instantiating them in a single class, responsible for holding the application's context (e.g., in `GlobalState`).

**Comment by jecluis** [comment]
@jhesketh any plans to work on this soon?

**Comment by jhesketh** [comment]
> @jhesketh any plans to work on this soon?

Ah, so this had kinda feel off my radar sorry! I'll try to have a poke at it tomorrow unless you have any thoughts on how to approach it?
