### ISSUE TITLE
libvirt storage caches stale box images

### ISSUE THREAD

**Issue by tserong** [aquarist-labs/aquarium#280]
It looks like I didn't _quite_ finish the job in #256. Even though an updated Vagrant box is added, when you `vagrant up`, somehow the image in libvirt's storage isn't updated to match the new box. No idea what's missing here, but I figured I'd better open an issue immediately so I didn't forget about it :-/

**Comment by tserong** [comment]
Oh FFS, turns out this is an 8 year old issue (see https://github.com/vagrant-libvirt/vagrant-libvirt/issues/85)

**Comment by tserong** [comment]
The manual solution is to remove the volume from libvirt with something like `virsh vol-delete --pool default aquarium_vagrant_box_image_0.img`

**Comment by s0nea** [comment]
If you're seeing something like:

```
$ virsh vol-delete --pool default aquarium_vagrant_box_image_0.img 
error: failed to get pool 'default'
error: Storage pool not found: no storage pool with matching name 'default'
```

it might be worth trying:

`$ sudo virsh vol-delete --pool default aquarium_vagrant_box_image_0.img`
