### ISSUE TITLE
glass: UX review

### ISSUE THREAD

**Issue by asettle** [aquarist-labs/aquarium#292]
**Is your feature request related to a problem? Please describe.**
I spoke to the UX Product Owner this afternoon and received some really helpful feedback on the process. Generally, she loved the installer look and feel.

**Describe the solution you'd like**
Few points she brought up that I think we can change for the better:

Installer notes:
1. When the bootstrap process and the node deployment is running, provide a checklist of items (and have them systematically check off when the process completes). This is useful as if the process continues for too long without information, the user might think it is broken and attempt to restart unnecessarily.

Dashboard notes:
1. The health bar appears to be missing information. Orange = warning, but this isn't clear, a label would help. The problem with icons by thesmelves is that they can easily be confused as something to hover over, rather than a source of information. There is enough room on the bar to include a label and an icon.
2. Capacity is good. However, the colours and the labels might need to be updated. The "unassigned" graph is highlighted red. Is it a warning that this space is not used? "Grey" or something more unassuming is a more suitable colour for unassigned space.
3. System information uses "used" and "free" as the language choices next to the graphs depicting capacity, however, capacity uses "unassigned and "assigned". It's important to use consistent language.
4. If we have navigation (like we did in the Ceph dashboard) keep to the left-hand side. If there will only be a few items to research, try using a menu bar at the top of the dashboard.

Layout notes:
- Swap system information with services (so that important information in colour and numbers) are together. This is because the user can gather information immediately from the images/graphs/numbers, whereas tables are together (services, hosts, volumes)  require further overview
- If the user is intended to interact with any of the volumes/hosts/services widgets, it might be worth having individual navigation sections rather than on the singular dashboard pane (for example, if the user goes up to 40, 50, 100 volumes, how is it going to be displayed properly without breaking the page? Or easily consumable?)

**Comment by votdev** [comment]
>     1. When the bootstrap process and the node deployment is running, provide a checklist of items (and have them systematically check off when the process completes). This is useful as if the process continues for too long without information, the user might think it is broken and attempt to restart unnecessarily.

This issue is already in progress by https://github.com/aquarist-labs/aquarium/pull/179 and https://github.com/aquarist-labs/aquarium/pull/187 but has not been merged till now because the solution is fragile and will break if the log output of cephadm changes. Currently cephadm does not forward the state of the deployment except writing log messages.

**Comment by votdev** [comment]
>     4\. If we have navigation (like we did in the Ceph dashboard) keep to the left-hand side. If there will only be a few items to research, try using a menu bar at the top of the dashboard.

We are currently unsure how much pages we will display in the dashboard. The number may increase by the time. IMO we should decide to switch the navigation layout in milestone 3 when we better know how much pages are used.

**Comment by votdev** [comment]
> Layout notes:
>     * If the user is intended to interact with any of the volumes/hosts/services widgets, it might be worth having individual navigation sections rather than on the singular dashboard pane (for example, if the user goes up to 40, 50, 100 volumes, how is it going to be displayed properly without breaking the page? Or easily consumable?)

Tables will have a paging navigation bar. By default only 5 rows will be displayed. If there are more, the user has no use the paging buttons to navigate through the rows.

![Bildschirmfoto vom 2021-03-12 12-11-10](https://user-images.githubusercontent.com/1897962/110932885-57d04a00-832c-11eb-904b-cb3989c261b9.png)

**Comment by s0nea** [comment]
I'm closing the issue because all topics are either addressed or covered in specific issues.
