### ISSUE TITLE
gravel: persistent state

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#32]
Ideally distributed from the start, with failover, etc.

Would be cool not having to reinvent the wheel.

I, personally, don't think relying on ceph-mon's config-key store is the right way to go.

**Comment by theanalyst** [comment]
How are we going for persistence here, a kv-store in hte likes of etcd/consul and the like or going native like rocksdb?

**Comment by tserong** [comment]
A thought that came up in one of our calls is to use ceph-mon's config store, but have a local cache of any details we need, on each aquarium node. So most of the time (when ceph is actually running) all aquarium nodes have access to everything. If the cluster is down (or, at least, the mons aren't in quorum), any individual aquarium node would fall back to using its local cache, until the cluster comes back. That means aquarium can still try to do something useful in the failure case, and also means we don't need a separate cluster aware / replicated config store.
