### ISSUE TITLE
glass: make health widget colors have more contrast

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#356]
![image](https://user-images.githubusercontent.com/506918/113004938-ebe34380-916b-11eb-86ae-14495782887b.png)

On a bright monitor, this white on yellow-ish makes it hard to read the text and see the icon.

I think we should either make it a darker yellow-ish, or make the text darker. :shrug:

**Comment by votdev** [comment]
The issue has been fixed with https://github.com/aquarist-labs/aquarium/pull/357.
Changed color theme from yellow/white to yellow/black according to EOS.

![Bildschirmfoto vom 2021-04-07 17-16-29](https://user-images.githubusercontent.com/1897962/113891593-7b6ca000-97c5-11eb-9666-64901243324e.png)
