### ISSUE TITLE
gravel: nfs-ganesha pool is created with size 3 by default

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#404]
The result is that we end up with an health warning once we add a second node, because the replication domain moves from `osd` to `host`, and we'll end up having this warning until we add a third node. This makes little sense to me.

The reason is simple: all pools are, by default and unless something is provided stating otherwise, created with size 3 by default.

This is configurable via the config option `osd_pool_default_size`.

Now, we're at a point where we must decide what we want to do about this: leave it as is, or adjust as we go?

My take is that we should, for a single node, drop it to 2, and increase it to 3 when we add a second node. However, this means we must be aware of which pools are not created by the user so we can adjust the redundancy ourselves on those. I think we already have all the infrastructure needed for this, by, essentially, running through all the pools and checking whether they match a service; if not, adjust.

Other thoughts?

@l-mb you might have a strong opinion on this one?

**Comment by l-mb** [comment]
For two nodes, size=3 can also not be reliably satisfied. That only starts making sense with at least three nodes?

**Comment by jecluis** [comment]
That's right. Push it to 3 on adding a third node makes more sense.
