### ISSUE TITLE
glass/gravel: provide item checklist while node bootstrapping/deploying

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#409]
I'm not really sure if, how and when it's feasible but https://github.com/aquarist-labs/aquarium/issues/292 suggests to show a checklist of action items while node bootstrapping/deploying:

> When the bootstrap process and the node deployment is running, provide a checklist of items (and have them systematically check off when the process completes). This is useful as if the process continues for too long without information, the user might think it is broken and attempt to restart unnecessarily.

**Comment by votdev** [comment]
Do we really want to show the user that e.g. OSD, MDS or any Ceph specific thing is deployed? The idea of Aquarium is to hide these Ceph specific issues. Showing the percentage progress is enough or maybe use generic messages instead of Ceph specific terms.

**Comment by votdev** [comment]
https://github.com/aquarist-labs/aquarium/pull/187

**Comment by votdev** [comment]
This issue should be discussed in the Aquarium group.

**Comment by asettle** [comment]
This issue is solved by the new navigation bar and the percentage tracker for the bootstrapping progress. Happy to close.
