### ISSUE TITLE
glass: CephfsModalComponent and NfsModalComponent refactoring

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#426]
The `CephfsModalComponent` and `NfsModalComponent` are quite similar. Add a more general component in order to get rid of the duplicated code.

Combine both components into a `FileServiceModalComponent` and add a selection box containing `CephFS` and `NFS` options.

**Comment by jecluis** [comment]
Can we increase the prio on this one from a Nice To Have to a Required? @votdev ? :)
