### ISSUE TITLE
glass: installer refactoring (horizontal stepper)

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#434]
Refactor the current installer in order to use an horizontal stepper for the whole process. It should improve the transparency for the user (e.g. the user sees he's at step 3 of 5 in the process currently) and make it easier for gravel to handle the deployment.

The horizontal stepper (and the installer) should contain the following steps:

**1. Host details**
- Hostname
- User information
  - name
  - password
  - real name
  - public key

**2. Networking**
- Set IPs for public- cluster-network
- NTP configuration

**3. Devices**
Show disk information

... (maybe some configurations more)

**4. Bootstrap**

**5. Summary and link to the dashboard**

The UI collects the information provided by the user through the various installer steps. It sends it to the backend in **one** request at the end of the installer. It should make it easier for the backend to e.g. handle a half the deployed system. If the user decides to close the installer during steps 1 - 3 and tries to resume later, he can just start at the beginning.

**Comment by jecluis** [comment]
One thing we kind of forgot is that step 5. should be "Service configuration", and dashboard and summary should be step 6. :)

**Comment by s0nea** [comment]
Ah... good point! To be precise I'm wondering how the whole installer process will look like, e.g. ...?

For creating a new cluster we do have the following currently:

1. Welcome
2. Installation mode (Create)
3. NTP configuration
4. Bootstrap
5. Node deployment (inventory + services deployment + link to the dashboard)

Will it then be:

<----  Start installer ---->
1. Welcome screen
2. Installation mode (Create new cluster)
3. Bootstrap
<----  Start horizontal stepper  ---->
4 a. Host details
4 b. Networking
4 c. Devices
4 d. Service deployment
4 e. Summary and link to the dashboard
<----  Stop horizontal stepper ---->
<----  Stop installer ---->

Or are we going to cover the whole installer by an horizontal stepper?

**Comment by jecluis** [comment]
> Will it then be:
> 
> <---- Start installer ---->
> 
>     1. Welcome screen
> 
>     2. Installation mode (Create new cluster)
> 
>     3. Bootstrap
>        <----  Start horizontal stepper  ---->
>        4 a. Host details
>        4 b. Networking
>        4 c. Devices
>        4 d. Service deployment
>        4 e. Summary and link to the dashboard
>        <----  Stop horizontal stepper ---->
>        <----  Stop installer ---->
> 
> 
> Or are we going to cover the whole installer by an horizontal stepper?

I'd say the horizontal stepper starts after 2, and Bootstrap it's a step that happens between 4c and 4d.

**Comment by jecluis** [comment]
Also, on the bootstrap page we could show a brief summary of what has been selected during the previous steps. Like

```
   Hostname: foo
   Username: bar
   NTP server: pool.ntp.org
   Front interface: eth0 172.20.20.30
   Back interface: eth1 172.20.21.30
   Devices:
       DeviceA    2TB
       DeviceB    2TB
       DeviceC    2TB
         Total        6TB

 <BOOTSTRAP?>
```

**Comment by s0nea** [comment]
> Also, on the bootstrap page we could show a brief summary of what has been selected during the previous steps.

Yes, I like the idea!
