### ISSUE TITLE
glass: add basic e2e (end-to-end) tests (Cypress)

### ISSUE THREAD

**Issue by callithea** [aquarist-labs/aquarium#45]
Write some basic tests to ensure the UI is working
For example:
 * Click through the navigation items and check the browser URL(s)
 * Since e2e tests are very time consuming when executing them it should be reduced to
   only cover user actions like creating/editing/deleting
   
Since we're already familiar with the test framework it would make sense to stick with Cypress.
We could also take over some e2e configuration files and simple e2e tests from our (upstream) dashboard development
to get started.

**Comment by s0nea** [comment]
In the today's upstream standup we had a look at the following topic https://github.com/TheBrainFamily/cypress-cucumber-preprocessor which looks really interesting to me.

**Comment by Devp00l** [comment]
Just looked into cucumber and it sounds promising. It will help us to follow the dry principle easily :) and therefore to write better and more useful e2e tests.

I watched this [video](https://www.youtube.com/watch?v=YV3qPvhJ-rg) and found a [course on oreilly](https://learning.oreilly.com/videos/cucumber-bdd-made/9781800568921/) about it.
