### ISSUE TITLE
glass: 'Join existing cluster' page helper(s)

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#451]
I think it would be nice to add a hint telling where the security token can be found to the 'Join existing cluster' page:

![Screenshot_2021-04-26_16-58-17](https://user-images.githubusercontent.com/8761082/116111317-d30c7600-a6b6-11eb-98b2-3217cc2d57ae.png)

I'm wondering if we should also add a note about how to get the IP address or FQDN.

**Comment by votdev** [comment]
The dialog that displays the token in the dashboard should maybe display the address, too.
