### ISSUE TITLE
glass/gravel: expose ceph-volume device availability

### ISSUE THREAD

**Issue by mgfritch** [aquarist-labs/aquarium#475]
Expose the reason as to why a device is not available.

In my case, I have two USB thumb drives:
* /dev/sdd (32gb)
* /dev/sde (4gb)

The device `/dev/sde` is rejected by ceph-volume because it is less than 5gb in size.

![aquarium_devices](https://user-images.githubusercontent.com/1752663/117084083-7850cb00-ad03-11eb-997a-5569868ae5df.png)

**Comment by jecluis** [comment]
This will require adding support for the reject messages in the inventory listing on gravel, I believe. It should be a trivial addition, and easily exposed.

I'd hold off on adding support to the current devices page until #509 is reviewed and merged.

**Comment by jecluis** [comment]
for what is worth, #518 will provide the reject reasons to the frontend, albeit it's not quite implemented yet. @s0nea are you actively working on this at the moment?

**Comment by s0nea** [comment]
Sorry for the late answer :disappointed: I missed the ping. No, I'm not working actively on the issue at the moment.
