### ISSUE TITLE
glass: Rename "Capacity" to "Allocated" in dashboard widgets

### ISSUE THREAD

**Issue by votdev** [aquarist-labs/aquarium#487]
Rename "Capacity" to "Allocated"

**Comment by votdev** [comment]
@jecluis Could you please name the widgets and texts that should be changed? Maybe adding a screenshot will help to identify them.

**Comment by jecluis** [comment]
@votdev I think I'll be renaming "reservation" to "allocation" in the backend as well, so I might just go through the frontend and change that where applicable. If you don't mind, can I take this ticket and run with it?
