### ISSUE TITLE
glass: Add time series dashboard widget

### ISSUE THREAD

**Issue by votdev** [aquarist-labs/aquarium#488]
Display time series delivered by Ceph.

**Comment by Devp00l** [comment]
To show the current read write status of the hole cluster (combining all osd read writes if not yet implement in ceph).

**Comment by AvengerMoJo** [comment]
Should this be something pulling from prometheus?

**Comment by jecluis** [comment]
> Should this be something pulling from prometheus?

I'm not so sure Prometheus is the right way to go, given it does not support replication; should we lose the prometheus instance, we lose the statistics.

However, https://cortexmetrics.io/ seems interesting and might be worth a look.

**Comment by AvengerMoJo** [comment]
> > Should this be something pulling from prometheus?
> 
> I'm not so sure Prometheus is the right way to go, given it does not support replication; should we lose the prometheus instance, we lose the statistics.
> 
> However, https://cortexmetrics.io/ seems interesting and might be worth a look.
Sounds great should we start pulling Prometheus and Cortex together and start testing? Looks like we need Prometheus in the back store and cortex to maintain the data distribution. Not sure how heavy it is going to be.
Should we store the monitoring data separately or inside ceph?
