### ISSUE TITLE
Create UI layout mapping between the virtual osd to physical HDD location for node creator. 

### ISSUE THREAD

**Issue by AvengerMoJo** [aquarist-labs/aquarium#498]
When an OSD is having an issue or an HDD required to be swap out. There isn't a consistent tool to allow system/service engineers to know exactly which slot or where the drive is actually located. In the field, engineers are most likely service use paper or sticker to label and identify the driver to the virtual OSD mapping e.g. row two, slot two is actually /dev/sdk and osd15 
There are libstoragemgmt tools to help identify the harddrive at the fail time if the controller is supported and or the LED/drive is still running. However, if the node fails and you get a hand full of 24 drivers and try to figure it out which is really hard. 

Instead of asking the SE to write down and map out the physical drive local, we create UI in the bootstrapping or adding node workflow to allow the user to set up the layout of the node e.g. tower vs rackmount, how many rows and columns, is the disk lay vertically or horizontally.

**Comment by AvengerMoJo** [comment]
Sample test with svg js to create a server layout SVG

https://jsfiddle.net/1bm5wpfg/

**Comment by AvengerMoJo** [comment]
Rackmount 2U, 1 Row, 24 Columns, 24 slots 2.5", Drive Vertical, NON-Hot-Swap 
![Rackmount 2U, 1 Row, 24 Columns, 24 slots 2.5", Drive Vertical, NON-Hot-Swap](https://www.supermicro.com/sites/default/files/2020-06/SYS-240P-TNRT_Front.png)(https://jsfiddle.net/AvengerMoJo/tb2wk8m4/20/)
Testing the script idea by calling 

`drawDriveLayout(draw, BoxType.Rackmount, 2, 1, 24, 24, DriveType.HDD25, SlotOrientation.Vertical);`

**Comment by AvengerMoJo** [comment]
Rackmount 7U, 16 Rows, 1 Column 16 slots 2.5", Drive Horizontal, Hot-Swap 
![Rackmount 7U, 16 Rows, 1 Column 16 slots 2.5", Drive Horizontal, Hot-Swap](https://www.supermicro.com/sites/default/files/2018-10/SYS-7089P-TR4T_Front.png)

(https://jsfiddle.net/AvengerMoJo/tb2wk8m4/26/)

![storage3](https://user-images.githubusercontent.com/109793/119794821-747f2580-bf0a-11eb-82de-05f948c4f568.jpg)

**Comment by AvengerMoJo** [comment]
Rackmount 2U, 3 Row, 4 Columns, (front 12, back 12) 24 slots 3.5", Drive Horizontal, Hot-Swap 
![Rackmount 2U, 3 Row, 4 Columns, (front 12, back 12) 24 slots 3.5", Drive Horizontal Hot-Swap](https://i.ebayimg.com/images/g/ru8AAOSwADZe6lrv/s-l1600.jpg)

`drawDriveLayout(draw, BoxType.Rackmount, 2, 3, 4, 24, DriveType.HDD35, SlotOrientation.Horizontal);`
![storage4](https://user-images.githubusercontent.com/109793/119880750-23e5e780-bf5f-11eb-9af5-a0ed265f1040.jpg)

**Comment by AvengerMoJo** [comment]
Rackmount 1U, 1 Row, 4 Columns, 12 slots 3.5", Drive Vertical, Hot-Swap
![Rackmount 1U, 1 Row, 4 Columns, 12 slots 3.5", Drive Vertical, Hot-Swap](https://www.anewtech.net/sites/default/files/pphoto/Anewtech-SSG-6019P-ACR12L%2B.jpg)

`drawDriveLayout(draw, BoxType.Rackmount, 1, 1, 4, 16, DriveType.HDD35, SlotOrientation.Horizontal);
`![storage5](https://user-images.githubusercontent.com/109793/119882232-c2bf1380-bf60-11eb-8aec-44c0dc582dcb.jpg)

**Comment by AvengerMoJo** [comment]
Tower 4U, 1 Row, 5 Columns, 5 slots 3.5", Drive Vertical, Hot-Swap 
![Tower 4U, 1 Row, 5 Columns, 5 slots 3.5", Drive Vertical, Hot-Swap](https://www.supermicro.com/a_images/products/views/8048B-TR3F_front.jpg)

`drawDriveLayout(draw, BoxType.Tower, 4, 1, 5, 5, DriveType.HDD35, SlotOrientation.Vertical);`

![storage6](https://user-images.githubusercontent.com/109793/119883160-ce5f0a00-bf61-11eb-93c8-ffee4cc1a873.jpg)

**Comment by AvengerMoJo** [comment]
Now the layout is being created, it is possible to create templates from the different storage systems. 
1) Do we need to maintain an online repo/database to keep track of all the storage system layout configuration. The data itself really small, basically the following 
a) Rack / Tower, 
b) Rack Height / Tower Width 
c) Row of drives
d) Column of drives
e) Total drive count ( we should able to get it from the system) 
f) HDD35, HDD25, SSD25
g) SlotOrientation Vertical  / Horizontal

**Comment by asettle** [comment]
Moved
