### ISSUE TITLE
gravel: add container image config items

### ISSUE THREAD

**Issue by mgfritch** [aquarist-labs/aquarium#514]
aquarium currently deploys the last stable ceph pacific container image:
https://github.com/ceph/ceph/blob/f908420004cc81a30edb2b252b4d92f50c526280/src/cephadm/cephadm#L49

This is currently set to the ceph v16.2.4 point release. However, breaking changes will be introduced by ceph v16.2.5

Likewise, a user might wish to redirect the aquarium to a private container repository (e.g. air-gap)

we should consider adding an aquarium config option that:
* defines the desired container images (ceph, etcd, prom, grafana, etc.)
* pass the desired ceph container image to each cephadm cmd
* set the desired config images in the mon config store
* co-ordinate the upgrade between the various aquarium components and ceph

**Comment by asettle** [comment]
Moved
