### ISSUE TITLE
OpenStack as a workload

### ISSUE THREAD

**Issue by l-mb** [aquarist-labs/aquarium#516]
As an administrator, I have an OpenStack setup that I want to back with storage from an Aquarium appliance.

I want to be able to specify this as one workload and have the setup optimized and enabling all features that are required for this use case, and deploy all implied services.

**Comment by AvengerMoJo** [comment]
I'm not sure I understand the requirement completely. If we are talking about just getting access from openstack to ceph, here should be all we needed: 

1) create openstack Cinder-Volume pool, Glance-Image Pool 
2) create key for client.cinder and client.glance keys 
3) send the key and the ceph.conf to the openstack node need access.  ( this need some kind of remote call or scp etc ) 

However, I don't fully get the "optimized and all features" part, maybe I need more clarification. Thanks

**Comment by asettle** [comment]
Moved
