### ISSUE TITLE
Issue Priority vs Aquarium Requirements Matrix

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#519]
_(edit: incorporated feedback from comments)_

In an attempt to keep track of importance of tasks outside a given milestone, I've created a new set of tags and have been assigning them to existing issues.

On the one hand, we now have importance for Aquarium as a project:

* Aquarium: Must Have - Something critically needed for Aquarium as a project
* Aquarium: Should Have - Something Aquarium should provide/have
* Aquarium: Would Have - Something Aquarium would have should there be spare cycles
* Aquarium: Won't Have - Something Aquarium will not have, i.e., Rejected.

And on the other, we have individual issue's priorities; these are independent from the importance for Aquarium, and reflect urgency in tackling an individual task:

* Prio: High - Something that is critically needed
* Prio: Medium - Something that is needed
* Prio: Low - Something that is non that very urgent

With that in mind, I've also created a matrix, that I see as a good rule of thumb for assigning issues to Milestones, as we work through the roadmap:

![Aquarium-Priorities](https://user-images.githubusercontent.com/506918/120178112-a806cc00-c1f8-11eb-9426-6a9f016d6827.png)

Thoughts?

**Comment by l-mb** [comment]
This looks good, as long as we're also tracking the two axes individually.

But does "must have" with "low priority" as recommended make sense? If it's "must", it's something Aquarium can't release without, which probably will never end up as "low" priority?

And finally - I'd suggest to also add "won't have" as a requirement level while we're revamping this. Documenting what we've explicitly decided against and being able to find those easily will be helpful.

**Comment by jecluis** [comment]
> This looks good, as long as we're also tracking the two axes individually.
> 
> But does "must have" with "low priority" as recommended make sense? If it's "must", it's something Aquarium can't release without, which probably will never end up as "low" priority?

My reasoning on that was that priority is quite a lot more mutable than the requirements, and represents a given item's priority in that point in time. I can see how a "must have" that is not expected for a few milestones could be low in priority, and have its priority gradually increasing over time as we near a state where that item becomes feasible.

> And finally - I'd suggest to also add "won't have" as a requirement level while we're revamping this. Documenting what we've explicitly decided against and being able to find those easily will be helpful.

Good point. Will add that to the matrix.

**Comment by jecluis** [comment]
![Aquarium-Priorities(1)](https://user-images.githubusercontent.com/506918/120178112-a806cc00-c1f8-11eb-9426-6a9f016d6827.png)

**Comment by asettle** [comment]
With the adjustment from Lars, I don't really have any other comments. I think we may have some initial confusion with people learning the difference between the axis, but I think it's easily learn. I assume we're going to document this in some form of "when you get started on the project" type thing? IE: https://github.com/aquarist-labs/aquarium/blob/main/CONTRIBUTING.md#submitting-bugs-and-requesting-new-features (this section may not be relevant enough - perhaps we add a new one)
