### ISSUE TITLE
[glass] Installer Arrow pointing to a opposite direction

### ISSUE THREAD

**Issue by AvengerMoJo** [aquarist-labs/aquarium#535]
First page installer create workflow the arrow point to a wrong direction. 
![aquarium-bug](https://user-images.githubusercontent.com/109793/120606517-d6e3a300-c481-11eb-9cea-a14f8ceb32e4.jpg)

**Comment by jecluis** [comment]
that's by design. Clicking on the arrow should bring the user to the previous step/screen.
