### ISSUE TITLE
Share read only Podman storage for the cluster using the same version of pod

### ISSUE THREAD

**Issue by AvengerMoJo** [aquarist-labs/aquarium#549]
After the first node is installed. The container image could be then share as read-only export for the rest of the cluster so every joined node will be running the same version of the pod. And reduce the overhead of pulling images from the internet for an individual node to install one by one. 

My idea is simply NFS export read only /var/lib/containers/ from the first node to the cluster internal network mask e.g. 192.168.128.* ( even better we can create an extra directory  in containers e.g. aquarium-pods ) 
When the second node joining. It expend the local /etc/containers/storage.conf additionalimagestores = [ aquarium-pods ]

**Comment by tserong** [comment]
I'm not sure about this. Since #464 we already include the ceph container image inside the aquarium image, so initial deployment should already be very quick without needing to pull images from the internet.

**Comment by tserong** [comment]
Also, there a tracker issue in upstream ceph, which proposes to solve this a different way, by deploying a local container registry (see https://tracker.ceph.com/issues/47286), although TBH, IMO that's not really something the Ceph cluster should be managing itself...
