### ISSUE TITLE
glass: allow selecting devices functions on 'devices' step

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#555]
During the installer's devices step, the user should be able to select the function of each available disk (system, storage, none), and then the installer should pass that on to the `/nodes/deployment/start` api call.

Depends on #554

**Comment by jecluis** [comment]
@votdev assigning this to you as well because you might have a better idea than I do how to achieve this. If you don't happen to have spare cycles to handle it (once the dependencies are in place), I'll be happy to take a crack at it.

**Comment by asettle** [comment]
Moved
