### ISSUE TITLE
glass: Basic support of i18n

### ISSUE THREAD

**Issue by votdev** [aquarist-labs/aquarium#56]
Implement the foundation for i18n support:

- Add ngx-translate
- Add scripts to extract translations
- ...

**Comment by asettle** [comment]
Two parts to this:

1. Implement the basics for milestone 2 (the more code we have, the more complicated it will be to go through the code and translate all the texts later). If we do it during development, it eases future pain. This does not mean actually translating the dashboard. But just adding a framework to prepare for translation. 
2. Implement further for milestone 3.
