### ISSUE TITLE
gravel/glass: add possibility to update NTP address configuration

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#562]
Give the administrator the possibility to update the NTP address configuration.

The following steps may have to be considered:

- gravel: re-add API endpoint to update the NTP address
- gravel: write NTP address to config file
- gravel: update NTP address value in etcd
- gravel: add etcd NTP address watcher
- gravel: update the NTP address on the local system as soon as the etcd value has been updated
- glass: re-add NTP service (PUT)
- glass: add configuration option/widget to the dashboard

**Comment by asettle** [comment]
Moved
