### ISSUE TITLE
Hosted demo

### ISSUE THREAD

**Issue by l-mb** [aquarist-labs/aquarium#567]
To attract more users and lower their barrier, it would be interesting to see if we could host an online version of the current state of Aquarium for new users to explore and play with.

This could either be a single shared instance (that gets wiped/reset ever so often), or possibly individual instances (if we can make that work somehow?).

**Comment by AvengerMoJo** [comment]
Any suggestion where should it be hosting? Should we point them to our labs vm from the public?

**Comment by l-mb** [comment]
> Any suggestion where should it be hosting? Should we point them to our labs vm from the public?

I don't think our current labs are best. I could see two approaches:

One, we host a public instance somewhere explicitly for that goal, deployed daily from the latest build and reset every hour or so. Problem is that multiple users would step on each other's toes ... Or maybe a read-only instance just for exploring?

Second, Amazon's Free Tier offers ~750h per month for up to 12 months. If we could make it easy to deploy on a public cloud _really easily_, they could just do that either with their own creds. I have no strong opinions on which cloud, but the more well-known, the easier we'll attract users ;-)

**Comment by AvengerMoJo** [comment]
@l-mb  thanks, let me see I can get in touch with the aws or google cloud for some credit or open source community promotion if possible.
