### ISSUE TITLE
glass: installer -> time card alignment seems to be wrong

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#571]
The card alignment of the time/NTP configuration within the installer seems to be wrong. As you can see on the screenshot below, the cards are aligned to the left. By increasing the window width the blank space on the right gets bigger and bigger. I do also have the feeling that the right card is bigger than the left one.

In my opinion the cards should be resized in order to fill the whole width. Also the right card should have the same width as the left.

Tested with Chrome Version 89.0.4389.82

![Screenshot_2021-06-15_10-52-37](https://user-images.githubusercontent.com/8761082/122031024-96afe900-cdce-11eb-8c7e-13957dc9fc43.png)

**Comment by votdev** [comment]
Maybe this is an `Angular Material` issue because we are currently on `12.0` and the latest version is `12.0.4`.

**Comment by votdev** [comment]
Can not reproduce this with Chrome `91.0.4472.114`.

![Bildschirmfoto vom 2021-07-12 12-43-08](https://user-images.githubusercontent.com/1897962/125274964-bf17fe00-e30e-11eb-8a12-9b8206d0456e.png)

**Comment by votdev** [comment]
Please reopen if the issue still exists. As mentioned above, can't reproduce the behavior with the mentioned browser versions.
