### ISSUE TITLE
aqrdev: create Vagrantfile with nvme disks

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#576]
Right now we're only creating HDDs with our generated deployment's Vagrantfile. This is because I haven't found a way to specify a different disk type to `vagrant-libvirt`.

However, some workarounds have been found, like [spdk's Vagrantfile](https://github.com/spdk/spdk/blob/9d4fbc135d6136b84b992c9ef373160eb7f0d6f5/scripts/vagrant/Vagrantfile), which achieve this by doing quite a bit of libvirt/qemu foo.

I was thinking it would probably be feasible if, instead of relying solely on `vagrant-libvirt`'s `storage` infrastructure, we could first create all disks (via aqrdev) with `virsh` and `qemu-img create`, and then pipe them into the Vagrantfile while adding the required `qemuargs` to make disks become nvme.

**Comment by AvengerMoJo** [comment]
spdk script using the following to create disk for nvme. I guess just not compressed. 
`qemu-img create -f raw "$nvme_disk" $size`
