### ISSUE TITLE
glass: allow configuring network devices during wizard's networking step

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#593]
The user should be able to configure the node's network interfaces during the wizard (depends on #591), specifying how these should be configured. These parameters should be provided to the deployment endpoint alongside the remaining configuration.

This includes

- [ ] DHCP
- [ ] static address
- [ ] bonding
- [ ] show interfaces grouped by NIC

**Comment by asettle** [comment]
Moved
