### ISSUE TITLE
glass/gravel: configure Network Interfaces

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#596]
A node may have one or more NICs, with one or more ports each. While we want to start up a node with dhcp enabled on all ports to be able to access said node's wizard for install/deployment, we need to allow the user to configure the node's interfaces as they wish.

- [ ] configure network interfaces from udev (#587)
- [ ] #590
- [ ] #591
- [ ] #592
- [ ] #593
- [ ] #594
- [ ] #595

**Comment by asettle** [comment]
Moved.
