### ISSUE TITLE
Explain `jenkins test` vs `jenkins run` (or remove one of them?)

### ISSUE THREAD

**Issue by tserong** [aquarist-labs/aquarium#709]
CONTRIBUTING.md says to run tests by adding comments to PRs which say `jenkins run tumbleweed` or `jenkins run leap`. 

.github/pull_request_template.md says the available Jenkins commands are:

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

What's the difference between "test" and "run"? Can we either explain this in more detail in our docs, or, alternately, can we _remove_ one of "test" or "run", to simplify this?

**Comment by jecluis** [comment]
@kshtsk mind taking care of this?

**Comment by kshtsk** [comment]
They are the same, synonims, so either can be used. If you have better idea how to explain it, you're welcome.

**Comment by kshtsk** [comment]
> Thanks, that clarifies things. Is it possible to only have one of the two? Either `test` or `run`? If not, choose one of the two and suppress the other in documentation to avoid confusion?

I added both for the convenience, because I use to use not only 'run' or 'test' keyword in different projects, so I don't break my brain trying to recall which one I have here.

**Comment by jecluis** [comment]
Okay, cool. Let's drop one of them, whichever you prefer. IMO it can be just from the docs.

**Comment by kshtsk** [comment]
@jecluis I prefer both, so let some else to drop either of them ;-)
