### ISSUE TITLE
Add progress for `podman pull` during deployment

### ISSUE THREAD

**Issue by tserong** [aquarist-labs/aquarium#753]
When bootstrapping a node, while we're pulling the container image, the UI says "Please wait, bootstrapping will be started", or "Please wait, start joining existing cluster" on join. It'd be really nice if we could somehow show the URL of the image being pulled, along with a progress display (something vaguely like what you get when you run `podman pull` from a terminal), so that you know what's going on, and when it's likely to finish.

Note: this may be less important if you're running a local registry and/or you have faster internet than rural Tasmania.

**Comment by jecluis** [comment]
This might not be trivial, but we should at least attempt to do it.
