### ISSUE TITLE
CPU load is rendered as a percentage, but should be a float

### ISSUE THREAD

**Issue by tserong** [aquarist-labs/aquarium#754]
The dashboard shows CPU load, something like:

```
1 min  5 min  15 min
  6%    14%     17%
```

But, assuming this is CPU load as you'd see with `top`, those values _aren't_ percentages.  They're more like a process/thread count, so should be rendered as raw numbers - 0.06, 0.14, 0.17 in the above example.

**Comment by jecluis** [comment]
I think this should be a percentage, but we need to ensure that all cores/cpus are accounted for. The problem is that I suspect this has only been tested with virtual images with a single cpu count.
