### ISSUE TITLE
Why allow custom container image to be specified when _joining_ node to existing cluster?

### ISSUE THREAD

**Issue by tserong** [aquarist-labs/aquarium#763]
Seen while testing #758. When joining a new node to an existing cluster, the Networking page asks if you want to use the default image, or a custom image. Why allow a different image to be specified for nodes that are joining? Shouldn't the image to use be a cluster-wide setting, and only need to be specified on the first node, when you create the cluster? Or am I missing something?

**Comment by jecluis** [comment]
Considering bug.
