### ISSUE TITLE
gravel: nfs support: creation via orchestrator interface

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#81]
Ensure we have support for the NFS client and operational management via the orchestartor interface. Consider:

- How to deploy NFS/bootstrap configuration
- Starting and restarting nfs (in the dashboard?)
- How to manage NFS exports
- Using CephFS or RGW as the backstore
- Using the dashboard to manage NFS ganesha config files
- Configuring multiple NFS ganesha clusters

**Comment by asettle** [comment]
@mgfritch update? :)

**Comment by jecluis** [comment]
reopening because the merged PR doesn't address the whole thing.
