### ISSUE TITLE
gravel: expose statistics and cluster status to be consumed by API users

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#88]
Consider:

Exposing information per-service:
- usage statistics
- read/write statistics
- how far/close usage is of predetermined capacity for service

General status of cluster:
- all nodes okay?
- some nodes are down?
- the cluster is dead?

**Comment by asettle** [comment]
@sebastian-philipp any update?

**Comment by jecluis** [comment]
Partially resolved by #331, #330, and #327
