### ISSUE TITLE
cli: investigate support options in case of cluster outage

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#92]
**Context**
At some point the cluster may be so borked that we might need to access the cluster via ssh and perform cli operations.
It would be nice to ascertain whether we're going to rely on the ceph tool, or something simpler.
And definitely how to allow the user to access the cluster.

**Comment by AvengerMoJo** [comment]
Assume our webservice is still running, we can include webssh in the interface for node login.

**Comment by jecluis** [comment]
@AvengerMoJo I think we might want to provide direct ssh access to the node in case the service has died for some reason, but the webssh is also a good idea.

I believe for us to pull this off we'll need to allow the user to add ssh pubkeys via the interface first. Or, at the bare minimum, allow them to set a password during deployment.

@AvengerMoJo would you like to take the lead on figuring out what might be required? We're not looking for an implementation just yet, just a list of what we might need to do to accomplish it in a future milestone.

**Comment by jecluis** [comment]
anyone wanting to take the lead on this?

**Comment by AvengerMoJo** [comment]
My idea is simple, just include webssh in each aquarium web service and it could be embedded in glass or trigger start by gravel as needed. Both solutions are possible.
Question: 

1) Do we want to pre-configure the ssh so it doesn't require password to login at all. ( assume vagrant and aquarium default password still in place and cluster internal network is secure ) 
2) This also assumes SSH is enabled and already available without the UI. If web service and UI is down I guess the user can still using console ssh. So we only need to create a UI in glass and API in gravel to start-stop sshd. Right?

**Comment by AvengerMoJo** [comment]
[WebSSH Python](https://pypi.org/project/webssh/ )
If we can install it in setup and run it in a port we assigned and embedded that in glass with a button to start and stop should be enough. Pre-configuration could be simple and no need for user to input beside the password etc.

**Comment by asettle** [comment]
Moved
